spring.application.name=crm
spring.datasource.url=jdbc:postgresql://localhost:5432/crm_db
spring.datasource.username=admin
spring.datasource.password=96778
spring.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
